### ISSUE TITLE
New users should be able to sign up

### ISSUE THREAD

**Issue by k-awe-some** [minhhvu/dooee-front-end#2]
**TO-DO Functionalities:**
- [ ] New accounts creating
- [ ] Error handling on inputs (name/email/password/confirm password)

**TO-DO Designs:**
- [ ] Basic UI/UX
- [ ] Mobile-first approach
